### ISSUE TITLE
Wanna contribute, but damn … project setup under macOS

### ISSUE THREAD

**Issue by maryisdead** [Emperorlou/Initium-ODP#1059]
First of all, sorry for posting this here as it's not really an issue. But I felt like this is the only place to get help for this.

I'm a full-time full-stack web dev with 20+ years of experience. I prefer working the front-end but have been on large-scale backend projects as well (mainly PHP, know a bit of Python).

I see so many things I'd love to improve on the front-end, even would clean up visuals and contribute images (know my way around image editing and have _some_ sense of what looks good and what's ugly).

But I've never touched anything Java. I tried setting this project up but didn't come very far. Java – or rather its environment – is just not very … approachable.

Anybody able to share a step-by-step guide on how to set this thing up under macOS and get it running?

I run on macOS Catalina 10.15.7 and usually use Visual Studio Code and TextMate but wouldn't mind installing another IDE for this.

Cheers
Matthias

**Comment by Emperorlou** [comment]
I can definitely help you out. We need to start by getting you on our
Slack, I just need an email address. You can email me at
***@***.***

**Comment by maryisdead** [comment]
At what? :D
