### ISSUE TITLE
Gradle?

### ISSUE THREAD

**Issue by apemanzilla** [Emperorlou/Initium-ODP#687]
Just found this and was wondering if you were familiar with Gradle. It would massively simplify IDE setup and a lot of other parts of the development cycle, but I wanted to ask if you were interested before I spend a bunch of time writing a PR for it.

**Comment by Emperorlou** [comment]
You know what... I'm open to it. I may not have a lot of time for the next 2 weeks, but I can still be reached sporadically. Are you in slack already?

**Comment by apemanzilla** [comment]
Not yet, you can find my email on my profile to send an invite. Thanks!

**Comment by Emperorlou** [comment]
We have now officially migrated to gradle!
