### ISSUE TITLE
Unable to open list of items for crafting

### ISSUE THREAD

**Issue by txtsd** [Emperorlou/Initium-ODP#782]
![screenshot](https://i.imgur.com/vLWDpeo.png)

**Comment by Emperorlou** [comment]
Yup I'm in the middle of a transition. Expect bumps in the invention system
until that is complete.

**Comment by txtsd** [comment]
Thanks for the quick reply.
I've been playing a lot lately and hope to be able to contribute soon!
Please close this issue once it's taken care of.

**Comment by Emperorlou** [comment]
This should be working now.
