### ISSUE TITLE
Shrinking Buttons

### ISSUE THREAD

**Issue by benmanuel12** [Emperorlou/Initium-ODP#785]
This may be an intended feature, but when I have an item in each hand on mobile and I tap the left hand one, it shrinks to the size of the loading bar and the right hand item button moves up next to it. It looks a bit odd. I can provide screenshots if you like.

**Comment by Emperorlou** [comment]
Yes please, a screenshot would help. Thanks!

**Comment by benmanuel12** [comment]
if it still applies
![image](https://user-images.githubusercontent.com/29860451/37490038-67da1cb2-2891-11e8-9dfa-8b55c017c431.png) before
![image](https://user-images.githubusercontent.com/29860451/37490054-7b79bfde-2891-11e8-882e-d05ec9b4d3f6.png)
after

**Comment by Emperorlou** [comment]
Yes this is intentional but I made A new system anyway ^^
