### ISSUE TITLE
"Internal Server Error"

### ISSUE THREAD

**Issue by Aphrodites1995** [Emperorlou/Initium-ODP#786]
Every time when I get to a new location, including combat sites, the site shows me this:

> Internal Server Error
There was an error when trying to perform the action. Feel free to report this on /r/initium. A log has been generated.

It only then works when I refresh the page.

**Comment by Emperorlou** [comment]
Ok we'll have to look into this. Does it happen always on all characters?

**Comment by Aphrodites1995** [comment]
No, it happened five days ago, when both the chat and the game didn't work.
