### ISSUE TITLE
Can't open chests in the inventory

### ISSUE THREAD

**Issue by not-IceMan** [Emperorlou/Initium-ODP#788]
Probably caused by the 14/02 major updates.

**Comment by not-IceMan** [comment]
This issue makes the game somehow unplayable, since I cannot open any inventory chests in order to switch gear. I'm not talking about multitab chars, that issue is well-known, I mean the main char.

**Comment by SPFiredrake** [comment]
#790 fixes this issue. Release incoming soon. @Emperorlou please close this issue when released.
