### ISSUE TITLE
Strength Requirement Indicator checks your strength after buffs, not your plain strength.

### ISSUE THREAD

**Issue by iamevanosity** [Emperorlou/Initium-ODP#798]
In this imaginary scenario, you have 6 strength. Your buffs bring you to 7 strength. You have two items in your inventory; one with a strength requirement of 6.5, one with a strength requirement of 7.5. You will be unable to equip either of them, but the red indicator will only appear for the one with 7.5 strength requirement.

**Comment by Emperorlou** [comment]
Should be fixed now and deployed.
