### ISSUE TITLE
Stat preview on mouseover from items in chat will scroll down the page proportional to how far down the chat is scrolled down.

### ISSUE THREAD

**Issue by iamevanosity** [Emperorlou/Initium-ODP#799]
Title should be totally descriptive. See figure 1 and figure 2; take note of the position of the stat preview popup compared to the position of the item (protector's helm) and the scroll bar for chat.

Also, this issue affects all browser types, but it was easier to screen capture on mobile.

Before chat is scrolled:
![figure1](https://user-images.githubusercontent.com/36278519/37319264-cf517146-2644-11e8-9d4c-0c153acc8a9d.png)

After chat is scrolled:
![figure2](https://user-images.githubusercontent.com/36278519/37319275-dfe5f00e-2644-11e8-8dd9-04233076a365.png)

**Comment by Emperorlou** [comment]
I also hate this bug.

**Comment by Emperorlou** [comment]
I know this is a bug but unfortunately I don't think I can easily fix it without major hacks. I have to close as a known issue.
