### ISSUE TITLE
Recurring Desktop Notifications

### ISSUE THREAD

**Issue by benmanuel12** [Emperorlou/Initium-ODP#801]
Whenever my computer reconnects to the internet, I get a desktop notification of a private message either sent from me or to me. This is probably the intended purpose of the notification. The issue is that the message is several weeks old and different each time. I am on Windows 10.

**Comment by Emperorlou** [comment]
This is a known issue, happens to me a lot. There is code in there that is supposed to fix it but it's clearly not working. It'll be fixed soon I hope.

**Comment by benmanuel12** [comment]
It's no concern to me, it just makes it hard to see if I have a new private message. I just thought it might be worth submitting an issue. I mentioned on my Initium group Discord and they posted this repo link.

**Comment by Emperorlou** [comment]
This should be fixed now.
