### ISSUE TITLE
"Light Fire" consuming Tinder even when attempt fails

### ISSUE THREAD

**Issue by Darcamer** [Emperorlou/Initium-ODP#809]
invention bug regarding the "Light Fire" option on campfires: if you don't have enough kindling in the kindling slot when you attempt it, it will consume the tinder in the tinder slot and still prevent you from lighting the fire

**Comment by Emperorlou** [comment]
I think this is actually intentional. Basically you try to light the fire, it burns a bit but goes out before you manage to build it up.
