### ISSUE TITLE
Desync OR Constant Notification

### ISSUE THREAD

**Issue by LordPixela** [Emperorlou/Initium-ODP#821]
After the new update, the party desync issue is mostly fixed. However, when i was playing for a while, it came back. Refreshing fixes the current UI desync, but the issue will come back when the leasder of the party moves again.

A separate partying bug is the following:
When the leader of the party does any action (i.e. moving, running, entering a fight), the other account in the party will get the notification that they are sending too much information in a short period of time. This is consistent and is not fixed by refreshing the page.

This can happen separately, or together.

**Comment by Emperorlou** [comment]
I think this is because I reverted to an earlier codebase to remove the PvP functions for some fixes. I'm creating a new bug report for the second issue mentioned though.
