### ISSUE TITLE
Loot window opening while enemy is still alive - Instead of Collect Gold/Pick Up, it shows 'attack'

### ISSUE THREAD

**Issue by LordPixela** [Emperorlou/Initium-ODP#826]
https://unsee.cc/4658c311/

^ that's a link showing the issue. This was preceded by a command error while attempting to run

**Comment by LordPixela** [comment]
Leave and forget worked

**Comment by LordPixela** [comment]
The command error happened again, here is the string.

There was a server error. You can report this to a dev if you'd like.Command: CombatEscape - Message: Index: 0, Size: 0

**Comment by LordPixela** [comment]
Server error*

**Comment by LordPixela** [comment]
It resulted in the same screen

**Comment by Emperorlou** [comment]
If it's not happening regularly then it's likely a transient database error
and those will happen from time to time.

**Comment by LordPixela** [comment]
Well it happened three times in less than an hour, so it seems pretty regular

**Comment by LordPixela** [comment]
Happened again but didnt open loot window. Btw at this point, enemy is still alive and i can just leave the combat site and forget it.

**Comment by Emperorlou** [comment]
Hopefully this is fixed now. If not we can reopen this task.
