### ISSUE TITLE
Instance text after defeating a monster, MORE button issue

### ISSUE THREAD

**Issue by BashfulRay** [Emperorlou/Initium-ODP#828]
Before, the MORE button after killing a monster had a nice little pop up that let you view the gear, mouse over it to see rolls, and drop things you didnt like, or drop all at your leisure.

This was very convenient, an awesome QoL feature, and a boon for people running instances consistently (generally speeding up clears a little, and making sure you didnt get overburdened and drop something cool).

The issue now is that it has been changed from this little pop-up to being displayed thru combat text in chat. If the monster partially blocks your winning attack and (especially if it drops more than just a few items) the items are all over chat, often  not fitting on the screen at the same time.

So you have to oftentimes view and item, then scroll down to see the drop button, drop, then scroll up to view the next item.... it's terribly cumbersome as often the items and the drop button arent displayed at the same time.

To further add to the cancer, if people are talking in chat the buttons and things MOVE with the flow of chat, meaning if it's moving fast you are playing catch up with the links.

It's extremely easy to drop things on accident, or drop the wrong items, or spend an extra several seconds trying to drop all on each mob, which adds a lot of time and reduces efficiency especially on instance clears with 50+ mobs in them.

Numerous players aside from just myself have requested to bring back the little pop up in the MORE link to display the instance loot. Pleaseeeeee revert this.

**Comment by Emperorlou** [comment]
Reverted.
