### ISSUE TITLE
Long-time inactive characters having their location set to nothing

### ISSUE THREAD

**Issue by perfecthaterd** [Emperorlou/Initium-ODP#829]
Location doesn't seem to set to their home town.

**Comment by Emperorlou** [comment]
This is by design and is an optimization.

**Comment by Emperorlou** [comment]
What is supposed to happen however is when they login for the first time, it then checks and sets their location to their home town.

**Comment by perfecthaterd** [comment]
It did not set the location to the home town for Glass Knight (Laso's alt). I had to do it manually

**Comment by Emperorlou** [comment]
Ok will fix
