### ISSUE TITLE
[QoL] Item Movement is clunky; drag and drop?

### ISSUE THREAD

**Issue by iamevanosity** [Emperorlou/Initium-ODP#853]
Being able to drag and drop items into containers and into houses would be cool.

**Comment by Emperorlou** [comment]
So much yes to this!

http://interactjs.io/ <-- This would be the perfect js lib to handle it too.

**Comment by Ashiix** [comment]
I can look into it

**Comment by Ashiix** [comment]
With my limited knowledge of the codebase, this seems like more trouble than it's worth. Why even bother with dragging when you can just click --> or <---, the only use case I could understand is changing the order of the character list, and I'm not sure if that's even possible as of now.

**Comment by Emperorlou** [comment]
The plan is to have a proper equipment doll one day. It would be nice to
not have to click those little arrows at some point and the drag and drop
would allow us to have a cleaner UI where we don't even have the arrows.

**Comment by Evanosity** [comment]
When I opened this issue I envisioned moving multiple items at once; having to click an arrow for every item can take ages. If you die with 100+ items in inventory it can take ages to pick them all up.

**Comment by Emperorlou** [comment]
I'm closing this because I kinda agree with the assessment that dragging/dropping is actually fairly tedious compared to a mode/state change where we allow multi-selection, and then subsequently perform some work on the selected items.
