### ISSUE TITLE
500 server error on die and became zombie, can't log in anymore

### ISSUE THREAD

**Issue by Kryth** [Emperorlou/Initium-ODP#959]
So i died while fighting with a Mutant Eel, i bacame a zombie, respawned at Aera and nearby character list showed up (idk why). The game "crashed" and every link, button etc gives me an 500 server error. 
"Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds."
I tryed to relog, but now just a blank white screen comes up with the same error message.

Character name: Krynir

I can make a new account, and that's works well.

Sorry for my english...

**Comment by Emperorlou** [comment]
Closing all old tickets. If this is still a problem please let me know and I'll reopen it!
