### ISSUE TITLE
enemy hp is hidden. 

### ISSUE THREAD

**Issue by CryBaby66** [Emperorlou/Initium-ODP#964]
![infinium 2](https://user-images.githubusercontent.com/71088664/92756799-25349d00-f35b-11ea-876d-3a8cdb594c16.PNG)

tried refreshing everything.

**Comment by Emperorlou** [comment]
Wow that's pretty wack. Is this the only monster it happens to?

**Comment by CryBaby66** [comment]
If its name sorter i get the hp bar where Afrit is located. If the name takes 2 lines i cant see a hp bar.

**Comment by Emperorlou** [comment]
I think this is fixed now
